add :keys opts with default false to stringify
am-kantox/elixir-iteraptor pull request #12
Opened 2020-05-14 19:32 UTC by sitch

2020-05-14 19:32 UTC, sitch commented
https://github.com/am-kantox/elixir-iteraptor/issues/11

2020-05-14 20:09 UTC, am-kantox requested changes

2020-05-14 20:09 UTC, am-kantox commented on lib/iteraptor.ex
> +          {k |> List.last() |> do_stringify(opts), jsonify(kw, opts)}
I would avoid repetitive `Keyword.get/3` calls and would do instead:

```elixir
  stringify_keys = Keyword.get(opts, :keys, true)
  Iteraptor.map(
    ...
    {k |> List.last() |> do_stringify(stringify_keys), jsonify(kw, opts)}
```

and see below.

2020-05-14 20:09 UTC, am-kantox commented on lib/iteraptor.ex
> +
```suggestion
  @spec do_stringify(any(), boolean()) :: any() | binary()
  defp do_stringify(k, false), do: k
  defp do_stringify(k, _) when is_atom(k), do: Atom.to_string(k) # faster
  defp do_stringify(k, _), do: to_string(k)
```

2020-05-21 21:31 UTC, sitch commented
Merged them!

2020-05-21 21:32 UTC, sitch commented
One other thing would be the typespec should technically change to `t:map/0` wasn't sure what you thought

2020-05-22 04:20 UTC, am-kantox approved these changes
:zap: :droplet: :zap: :gem: :zap: :blue_heart: :zap:

2020-05-22 04:21 UTC, merged